WebDevelopment/HRM/HRM.Web/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HRM.Web.Data;
using HRM.Web.Models;

namespace HRM.Web.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly HRMDbContext _context;

        public DepartmentsController(HRMDbContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            if (_context.Departments == null)
                return Problem("Entity set 'HRMDbContext.Departments'  is null.");

            var departments = await _context.Departments.ToListAsync();

            return View(departments);
        }

        
        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Departments == null)
            {
                return Problem("Entity set 'HRMDbContext.Departments'  is null.");
            }
            var department = await _context.Departments.FindAsync(id);
            if (department != null)
            {
                _context.Departments.Remove(department);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
          return (_context.Departments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebDevelopment/HRM/HRM.Web/Controllers/DesignationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HRM.Models;
using HRM.Web.Data;

namespace HRM.Web.Controllers
{
    public class DesignationsController : Controller
    {
        private readonly HRMDbContext _context;

        public DesignationsController(HRMDbContext context)
        {
            _context = context;
        }

        // GET: Designations
        public async Task<IActionResult> Index()
        {
            return _context.Designations != null ?
                        View(await _context.Designations.ToListAsync()) :
                        Problem("Entity set 'HRMDbContext.Designations'  is null.");
        }

        // GET: Designations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Designations == null)
            {
                return NotFound();
            }

            var designation = await _context.Designations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (designation == null)
            {
                return NotFound();
            }

            return View(designation);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Role")] Designation designation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(designation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(designation);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Designations == null)
            {
                return NotFound();
            }

            var designation = await _context.Designations.FindAsync(id);
            if (designation == null)
            {
                return NotFound();
            }
            return View(designation);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Designation designation)
        {
            if (id != designation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(designation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DesignationExists(designation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(designation);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Designations == null)
            {
                return NotFound();
            }

            var designation = await _context.Designations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (designation == null)
            {
                return NotFound();
            }

            return View(designation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Designations == null)
            {
                return Problem("Entity set 'HRMDbContext.Designations'  is null.");
            }
            var designation = await _context.Designations.FindAsync(id);
            if (designation != null)
            {
                _context.Designations.Remove(designation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DesignationExists(int id)
        {
            return (_context.Designations?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebDevelopment/HRM/HRM.Web/Controllers/EmployeeController.cs
using HRM.ViewModels;
using HRM.Web.Data;
using HRM.Web.Mapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HRM.Web.Controllers;
public class EmployeeController : Controller
{
    private readonly HRMDbContext db;
    public EmployeeController(HRMDbContext _db)
    {
        db = _db;
    }

    public async Task<IActionResult> Index()
    {
        if (db.Employees == null)
            return Problem("Employees dbset don't exist");

        var employees = await db.Employees.
            Include(e => e.Department).
            Include(e => e.Designation).
            ToListAsync();

        var employeesViewModels = employees.ToViewModel();

        return View(employeesViewModels);
    }

    public async Task<IActionResult> Add()
    {
        var departments = await db.Departments.ToListAsync();
        var selectListItems = departments.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
        ViewData["DepartmentList"] = selectListItems;

        var designations = await db.Designations
            .Select(d => new SelectListItem { Text = d.Title, Value = d.Id.ToString() }).ToListAsync();
        ViewData["DesignationList"] = designations;

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(EmployeeViewModel employeeViewModel)
    {
        var profileRelativePath = SaveProfileImage(employeeViewModel.profileImage);
        employeeViewModel.ProfileImageName = profileRelativePath;
        var employee = employeeViewModel.ToModel();

        await db.Employees.AddAsync(employee);

        await db.SaveChangesAsync();

        return RedirectToAction("Index");

    }

    public IActionResult Edit(int? id)
    {
        if (id == null)
            return NotFound();

        var employee = db.Employees
           .Include(e => e.Department)
          .Include(e => e.Designation)
          .FirstOrDefault(e => e.Id == id);

        if (employee is null)
            return NotFound();

        var employeeViewModel = employee.ToViewModel();
       
        var departments = db.Departments.ToList();
        var selectListItems = departments.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
        ViewData["DepartmentList"] = selectListItems;

        var designations = db.Designations
            .Select(d => new SelectListItem { Text = d.Title, Value = d.Id.ToString() }).ToList();
        ViewData["DesignationList"] = designations;


        return View(employeeViewModel);
    }

    [HttpPost]

    public IActionResult Edit(EmployeeViewModel employeeViewModel)
    {
        var employeevm = employeeViewModel.ToModel();
        db.Update(employeevm);
        db.SaveChanges();

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Delete(int id)
    {
        var employee = db.Employees.Find(id);
        var employeemodel = employee.ToViewModel();

        return View(employeemodel);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(EmployeeViewModel employeeViewModel)
    {

        var employee = employeeViewModel.ToModel();

        if (employee == null)
        {
            return NotFound();
        }

        db.Employees.Remove(employee);
        await db.SaveChangesAsync();

        return RedirectToAction("Index");
    }


    private string SaveProfileImage(IFormFile file)
    {
        var fileName = file.FileName; 
        var indexOfDot = fileName.LastIndexOf(".");
        var fileExtenstion = fileName.Substring(indexOfDot);
        var profileRelativePath = $"images/profiles/{Guid.NewGuid()}{fileExtenstion}";
        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", profileRelativePath);

        using var stream = System.IO.File.Create(filePath);
        file.CopyTo(stream);

        return profileRelativePath;
    }
}

WebDevelopment/HRM/HRM.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRM.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/HRM.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/hr.jpg" height="40" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Employees
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Employee" asp-action="Index"><i class="bi bi-list-ol"></i> All Employees</a></li>
                                <li><a class="dropdown-item" asp-controller="Employee" asp-action="Add"><i class="bi bi-plus-lg"></i> New Employee</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-controller="Departments" asp-action="Index">
                                        <i class="bi bi-list-ol"></i> All Departments
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Departments" asp-action="Create">
                                        <i class="bi bi-plus-lg"></i> New Department
                                    </a>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Designations" asp-action="Index">
                                        <i class="bi bi-list-ol"></i> All Designations
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Designations" asp-action="Create">
                                        <i class="bi bi-plus-lg"></i> New Designation
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 HRM Portal - From .Net Group
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>